version: "3.3"

services:

    #Laravel app
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: genesis-api
        container_name: genesis-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - genesis

    #nginx service
    nginx:
        image: nginx:alpine
        container_name: genesis-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - genesis

networks:
    genesis:
        driver: bridge
